config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#index"
  get :upload, action: :upload, controller: :pages
  post :upload_game, action: :upload_game, controller: :pages
  post :next_generation, action: :next_generation, controller: :games


  resources :games, only: [ :index, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user

  validates_presence_of :rows, :columns, :matrix

  validate :check_matrix_format


  def check_matrix_format
    if parsed_matrix.length != rows
      errors.add(:matrix, "Invalid rows")
    end
    parsed_matrix.each do |row|
      if row.length != columns or (row.index(".").nil? && row.index("*").nil?)
        errors.add(:matrix, "Invalid Columns")
        break
      end
    end
    parsed_matrix.each do |row|
      row.each do |cell|
        if cell != "*" && cell != "."
          errors.add(:matrix, "Invalid cell")
          break
        end
      end
    end
  end


  def parsed_matrix
    JSON.parse(matrix)
  end

  def next_generation
    new_matrix = parsed_matrix
    new_matrix.each_with_index do |row, i|
      row.each_with_index do |cell, j|
        current_cell_state = parsed_matrix[i][j]
          if new_matrix[i][j] == "*" && (calculate_neighbours(i, j) < 2 || calculate_neighbours(i, j) > 3)
            new_matrix[i][j] = "."
          elsif new_matrix[i][j] == "." && (calculate_neighbours(i, j) == 3)
            new_matrix[i][j] = "*"
          else
            new_matrix[i][j] = current_cell_state
          end
      end
    end
    new_matrix
  end

  private
  def calculate_neighbours(x, y)
    sum = 0
    (-1..1).each do |i|
      (-1..1).each do |j|
        # Se ho 4 righe, x sarà compreso tra 0 e 3.
        # Mi trovo sulla coordinata x (riga) == 0, quindi x = 0, cerco i vicini (che in questo caso equivale a x = 3, cioè l'elemento opposto, per
        # calcolarlo prendo x = 0, i = -1 (cerco tra la riga sopra la mia), ci aggiungo 4, la somma è pari a 3; 3 % 4 è uguale a 3). Facendo questo
        # per le righe e le colonne, posso calcolare i miei vicini in posizione opposta
        row = (x + i + rows) % rows
        col = (y + j + columns) % columns
        sum += value(parsed_matrix[row][col])
      end
    end
    # Tolgo il valore di se stesso dalla somma
    sum -= value(parsed_matrix[x][y])
    sum
  end

  def value(symbol)
    val = 0
    if symbol == "*"
      val = 1
    end
    val
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  def index
    @games = Game.all.where(user: current_user)
  end

  def show
    @game = Game.find(params[:id])
  end

  def next_generation
    game = Game.find(params[:game_id])
    new_matrix = game.next_generation
    old_title_index = game.title.split(" ").last.to_i
    new_title = "Generation #{old_title_index + 1}"
    game.update_attribute("matrix", new_matrix)
    game.update_attribute("title", new_title)
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace("game", partial: "components/game_grid", locals: { game: game }) }
      format.turbo_stream { render turbo_stream: turbo_stream.replace("animation_controls", partial: "components/pause_game_button") }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [ :upload ]
  include PagesHelper
  def index
  end

  def upload
  end

  def upload_game
    unless params[:file].present?
      render :upload, status: :unprocessable_entity, alert: "You're missing to upload the .txt file"
    end
    file_ext = File.extname(params[:file])
    unless file_ext == ".txt"
      flash[:alert] = "Wrong file format, please upload a .txt file"
      render turbo_stream: turbo_stream.action(:redirect, request.referer)
      return
    end
    file_content = File.read(params[:file])
    title = extract_title(file_content)
    dimensions = extract_dimensions(file_content)
    rows = dimensions[:rows]
    columns = dimensions[:cols]
    matrix = extract_matrix(file_content)
    if is_matrix_valid?(file_content, rows, columns)
      @game = Game.create!(rows: rows, columns: columns, matrix: matrix, user: current_user, title: title)
      if @game.save
        flash[:notice] = "Game created correctly, now you can play the game!"
        render turbo_stream: turbo_stream.action(:redirect, game_path(@game))
      else
        render :upload, status: :unprocessable_entity, alert: "Invalid file format"
      end
    else
      render :upload, status: :unprocessable_entity, alert: "Invalid file format"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

# rubocop:disable Metrics/AbcSize, Metrics/MethodLength
# devise helper
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, "- #{msg}.") }
                       .join
    sentence = I18n.t(
      "errors.messages.not_saved",
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = "Ooops!"
    if resource.errors.count == 1
      message =  resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{message}.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, "#{msg}.") }
                         .join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end
# rubocop:enable Metrics/AbcSize, Metrics/MethodLength

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def extract_title(content)
    content.lines.first.strip.split(":").first
  end
  def extract_dimensions(content)
    dimension_line = content.lines[1].strip
    rows, cols = dimension_line.split.map(&:to_i)
    { rows: rows, cols: cols }
  end
  def extract_matrix(content)
    matrix_lines = content.lines[2..-1]
    matrix = matrix_lines.map { |line| line.strip.chars }
    matrix
  end

  def is_matrix_valid?(content, rows, columns)
    v = false
    matrix_lines = content.lines[2..-1]
    matrix = matrix_lines.map { |line| line.strip.chars }
    if matrix.length == rows && matrix[0].length == columns
      v = true
    end
    v
  end
end

app/views/games/index.html.erb
<div class="page-margin">
  <div class="px-4 sm:px-8 grid grid-cols-2 lg:grid-cols-4 gap-4 my-8 animate-fade-in">
    <% @games.each_with_index do |game, index| %>
    <% colors = [ "bg-red-100", "bg-blue-100", "bg-emerald-100", "bg-yellow-100", "bg-violet-100", "bg-orange-100", "bg-stone-100", "bg-purple-100" ] %>
    <% color = colors.shuffle.first %>
      <%= link_to game_path(game), class: "#{color} flex items-center justify-center aspect-video rounded-xl hover:opacity-85" do %>
        <p class="text-xl font-semibold"><%= game.title %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="page-margin">
    <%= link_to "← Back", games_path, class:"mt-4 ml-4 sm:mt-8 sm:ml-8 table animate-fade-in", data: {turbo: false} %>
        <div class="px-4 sm:px-8 max-w-md mx-auto min-h-screen flex items-center animate-fade-in">
        <div class="w-full" data-controller="game" data-game-id-value="<%= params[:id] %>">
            <%= render '/components/game_grid', game: @game %>
            <div class="flex flex-wrap justify-center items-center mt-8 gap-8">
                <%= button_to "Next Generation ->", :next_generation, params: {game_id: @game.id},  class: "btn-primary" %>
                <%= render '/components/play_game_button' %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sb Extendi Gol" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice || alert %>
      <%= render '/components/flash_notice' %>
    <% end %>
    <%= render '/components/header' %>
    <main class="<%= params[:controller].include?('devise') ? "min-h-screen max-w-sm mx-auto flex items-center justify-center" : "" %>">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<div class="bg-white">
  <div class="min-h-screen relative px-6 pt-16 lg:px-8 flex items-center justify-center">
    <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
      <div class="text-center animate-fade-in">
        <h1 class="text-4xl font-bold tracking-tight text-dark sm:text-6xl">Welcome to the Game of Life</h1>
        <p class="mt-6 text-lg leading-8 text-gray-600">Upload your matrix and see what's going to happen</p>
        <%= content_tag "div", class: "mt-10 flex items-center justify-center gap-x-6" do %>
          <%= link_to "Start the game", current_user ? upload_path : new_user_session_path, class: "btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/upload.html.erb
<div class="page-margin">
    <div class="max-w-md mx-auto my-20 animate-fade-in px-4">
        <h1 class="w-full text-2xl sm:text-3xl font-bold text-center text-black mb-8">Welcome to the game <%= current_user.email %></h1>
        <p class="mb-8 text-sm">Here you can play the "Game of Life" by uploading the game matrix in file with .txt extension, ensure that contains this format:</p>
        <pre class="whitespace-pre-line flex justify-center mb-8">
            Generation 1:
            4 8
            ........
            ........
            ...*....
            ........
        </pre>
        <p class="mb-8 text-sm"">Where the first line is the generation number, the second line is the matrix size (X rows, Y columns), and the next lines are the matrix itself, where the dot (.) is a died cell, the * is a live cell</p>
        <p class="mb-8 text-sm"">If you need a template, here is one: <a href="/entry.txt" download class="underline">download template</a></p> 
        <%= render '/components/upload_matrix_form' %>
    </div>
</div>